name: Gerar_SkyPlus_IPA
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout_Codigo
        uses: actions/checkout@v3

      - name: Instalar_Theos
        run: |
          export THEOS=/Users/runner/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          
      - name: Compilar_Mod
        run: |
          export THEOS=/Users/runner/theos
          make package
          
      - name: Entregar_Arquivo
        uses: actions/upload-artifact@v3
        with:
          name: SkyPlus-IPA-Pronto
          path: packages/*.deb
